######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 8 13:42:41 2012
######################################################################

TEMPLATE = app
TARGET = IIDE
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS +=  iiBase.h iiTextDialog.h
SOURCES +=  IIDE.cpp \
            iiBase.cpp iiTextDialog.cpp

